//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortuga_Bezrukov.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public Nullable<int> IDBakery { get; set; }
        public Nullable<int> IDBeverage { get; set; }
        public Nullable<int> IDSalad { get; set; }
        public Nullable<int> IDDish { get; set; }
        public decimal FinalCost { get; set; }
        public Nullable<int> IDTable { get; set; }
    
        public virtual Bakery Bakery { get; set; }
        public virtual Beverage Beverage { get; set; }
        public virtual Dish Dish { get; set; }
        public virtual Salad Salad { get; set; }
        public virtual Table Table { get; set; }
    }
}
